apiVersion: v1
kind: Service
metadata:
  name: {{ template "CGW.fullname" . }}
  labels:
    app: {{ template "CGW.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  {{ if not .Values.service.externalIPs }}type: {{ .Values.service.type }}{{ end }}
  {{ if .Values.service.externalIPs }}externalIPs: {{ .Values.service.externalIPs }}{{ end }}
  ports:
    - port: 500
      targetPort: 500
      protocol: UDP
      name: p500
    - port: 4500
      targetPort: 4500
      protocol: UDP
      name: p4500
    {{- if .Values.vxlan.enabled }}
    - port: 4789
      targetPort: 4789
      protocol: UDP
      name: vxlan
    {{- end }}
  selector:
    app: {{ template "CGW.name" . }}
    release: {{ .Release.Name }}
